words = `India’s constitutional courts have rightly been concerned with the apparent administrative and institutional collapse while the Covid-19 pandemic is ravaging with its deadliest surge thus far. The courts have stepped in, raising the necessary red-flags on various glaring gaps in the management of the crisis be it supply of essential medicines, capping the price of necessary investigations, questioning dual pricing of vaccines and, most recently, ensuring continuous and judicious supply of oxygen to the States. To the grieving and anxious victims of this lethal pathogen, the courts have provided a critical support system and displayed much needed empathy, which is appreciable indeed. But while holding the Executive to account is a laudable goal, some recent decisions appear to be inadvertent forays into the domain of policy-making. The immediate context is the constitution of a National Task Force made up of well-known doctors, epidemiologists and academics. Among other things, this group will also look into issues related to oxygen availability and apportionment. Yet, there is no representative in the committee from the oxygen producing companies or from the logistics sector tasked with moving the critical gas across the country. These are the experts who are aware of the pain points related to oxygen supply. As we now know, availability of oxygen was not so much the problem as its transportation from far-off factories to the pandemic ravaged metros.

Be that as it may, the primary responsibility for ensuring healthcare for all rests with the Centre and the State governments and there already exists a system to deal with every possible aspect of Covid-19 management. If the system is ineffective or has failed — as indeed is the case now — the Court has the right to call the Executive to account, ask for explanations and demand corrective action. This would be within the judicial domain as also the fulfilment of a constitutional duty as the guardian of the fundamental rights of each bereaved family which has lost a member to lack of access to oxygen. But, for the Court to assume the role of the Executive is not the answer to the problem.

By creating an alternative, judicially-empowered task force, both the Centre and the States have been absolved of all responsibilities. Furthermore, there is neither Legislative nor Executive oversight over individuals on whom responsibilities have now been vested. They are not answerable to the people whereas the Court has empowered them to exercise immense power over policy-making. It will be very convenient for the Centre now to entrust all responsibilities to the task force and thus whitewash its poor handling of the crisis. Indeed, the Centre’s request to the Court to set up this committee indicates such a line of thought. Judicial interventions have thus far steered the public through an extremely traumatic period. The courts would do well to stay this course and hold the Executive to account, and not stray into the policy-making domain.`;

num = words.split(' ');

for (i = 0; i < num.length; i++) {
    console.log(i+1);
}